import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Custom ordering:
  // 1. Table of Contents
  // 2. Parts 1–7
  // 3. Front/Back matter and Appendices
  // 4. Index (at the end)
  tutorialSidebar: [
    // Table of Contents at the very top
    'toc',

    // Main parts in reading order
    {
      type: 'category',
      label: 'part1',
      items: [{ type: 'autogenerated', dirName: 'part1' }],
    },
    {
      type: 'category',
      label: 'part2',
      items: [{ type: 'autogenerated', dirName: 'part2' }],
    },
    {
      type: 'category',
      label: 'part3',
      items: [{ type: 'autogenerated', dirName: 'part3' }],
    },
    {
      type: 'category',
      label: 'part4',
      items: [{ type: 'autogenerated', dirName: 'part4' }],
    },
    {
      type: 'category',
      label: 'part5',
      items: [{ type: 'autogenerated', dirName: 'part5' }],
    },
    {
      type: 'category',
      label: 'part6',
      items: [{ type: 'autogenerated', dirName: 'part6' }],
    },
    {
      type: 'category',
      label: 'part7',
      items: [{ type: 'autogenerated', dirName: 'part7' }],
    },

    // Supporting sections after the main parts
    {
      type: 'category',
      label: 'front-matter',
      items: [{ type: 'autogenerated', dirName: 'front-matter' }],
    },
    {
      type: 'category',
      label: 'back-matter',
      items: [{ type: 'autogenerated', dirName: 'back-matter' }],
    },
    {
      type: 'category',
      label: 'appendices',
      items: [{ type: 'autogenerated', dirName: 'appendices' }],
    },
  ],
};

export default sidebars;
